### ISSUE TITLE
plotPS enhancements: adding information about equipoise

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortMethod#40] opened 2015-11-20 17:59 UTC
On the propensity score distribution plot, could we add some statistics like:
- total cohort size in treated/comparator  (perhaps "n=xxx' on the legend)
- % of treated/comparator group in clinical equipoise (e.g. % with 0.4<=PrefScore<=0.6)
- % of treated/comparator group without overlap

**Comment by schuemie** [comment] 2018-06-14 06:35
Duplicate of https://github.com/OHDSI/CohortMethod/issues/67

**Closed by schuemie** 2018-06-14 06:35 UTC
Labels: enhancement
